import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Button from '../../components/Button';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';

export default function PortfolioDetails() {
  const router = useRouter();
  const portfolioId = router.query.portfolioId;
  return (
    <>
      <Head>
        <title>Portfolio - {portfolioId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Nuestros Proyectos"
          bgSrc="/images/service_hero_bg.jpeg"
          pageLinkText={portfolioId}
        />
        <Spacing lg="90" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading title="Como trabajamos?" subtitle="Nuestro proceso creativo">
                <Spacing lg="40" md="20" />
                <p>
                  En nuestro proceso de desarrollo de sitios y software,
                  el cliente siempre es el centro.
                  <Spacing lg="10" md="30" />
                  Comenzamos con una reunión inicial para entender a fondo sus necesidades,
                  objetivos y expectativas.
                  <Spacing lg="10" md="30" />
                  Cada proyecto es único, por lo que nos aseguramos de ofrecer soluciones personalizadas que se adapten perfectamente a su visión.
                  Trabajamos de manera colaborativa en cada etapa, desde la planificación hasta la implementación,
                  manteniendo una comunicación clara y constante.
                  <Spacing lg="10" md="30" />
                  Nuestro objetivo es no solo entregar un producto final, sino construir una relación de confianza y satisfacción a largo plazo.
                </p>


              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-lg-1">
              <Spacing lg="60" md="40" />
              <h2 className="cs-font_30 cs-font_26_sm cs-m0">Nuestro enfoque</h2>
              <Spacing lg="50" md="30" /><hr />
              <Div className="row">

                <p>
                  Nos enfocamos en un proceso ágil que permite ajustar el proyecto conforme avanzamos,
                  asegurando que cumplimos con las metas del cliente en cada fase.
                  <Spacing lg="10" md="30" />
                  Comenzamos con un análisis detallado de sus requerimientos y le brindamos una propuesta clara.
                  <Spacing lg="10" md="30" />
                  Durante el desarrollo, dividimos el trabajo en ciclos cortos para recibir retroalimentación continua.
                  Esto nos permite entregar resultados rápidos y adaptarnos a posibles cambios.
                  <Spacing lg="10" md="30" />
                  Además, mantenemos al cliente informado con actualizaciones frecuentes, garantizando total transparencia desde el inicio hasta la entrega final del proyecto.
                </p>

              </Div>
            </Div>
          </Div>
          <Spacing lg="65" md="10" />
          <Div className="cs-page_navigation cs-center">
            <img
              src="/images/project.jpg"
              alt="Details"
              className="cs-radius_15 w-100"
            />
          </Div>
        </Div>
        <Spacing lg="145" md="80" />
        <Cta
          title="info@letdev.com.ar"
          bgSrc="/images/cta_bg_2.jpeg"
          variant="rounded-0"
        />
      </Layout>
    </>
  );
}
