import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Accordion from '../../components/Accordion';
import Button from '../../components/Button';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import IconBox from '../../components/IconBox';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import TestimonialSlider from '../../components/Slider/TestimonialSlider';
import Spacing from '../../components/Spacing';

export default function ServiceDetails() {
  const router = useRouter();
  const serviceId = router.query.serviceId;
  return (
    <>
      <Head>
        <title>Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Servicios"
          bgSrc="/images/service_hero_bg.jpeg"
          pageLinkText={serviceId}
        />
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Proceso de trabajo en desarrollo"
            subtitle="Desarrollo"
            variant="cs-style1 text-center"
          />
          <Spacing lg="90" md="45" />
          <Div className="row">
            <Div className="col-lg-4">
              <IconBox
                icon="/images/icon1.svg"
                title="Planificación"
                subtitle="Nos aseguramos de comprender tus necesidades y objetivos para crear un plan detallado que guíe todo el proceso de desarrollo de software, minimizando errores y maximizando la eficiencia."
              />
              <Spacing lg="30" md="30" />
            </Div>
            <Div className="col-lg-4">
              <IconBox
                icon="/images/icon2.svg"
                title="Diseño y Arquitectura"
                subtitle="Diseñamos soluciones a medida con una arquitectura sólida, asegurando que el software sea escalable, eficiente y fácil de mantener a largo plazo."
              />
              <Spacing lg="30" md="30" />
            </Div>
            <Div className="col-lg-4">
              <IconBox
                icon="/images/icon3.svg"
                title="Desarrollo y Pruebas"
                subtitle="Implementamos funcionalidades robustas y realizamos pruebas exhaustivas para garantizar que el software funcione de manera fluida, sin errores y cumpla con tus expectativas."
              />
              <Spacing lg="30" md="30" />
            </Div>
          </Div>
        </Div>

        <Spacing lg="120" md="50" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <img
                  src="/images/coding.png"
                  alt="Service"
                  className="cs-radius_15 w-100"
                />
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <h2 className="cs-font_50 cs-m0">
                Nuestros principales servicios
              </h2>
              <Spacing lg="50" md="30" />
              <Div className="row">
                <Div className="col-lg-6">
                  <Button
                    btnLink="/about"
                    btnText="Desarrollo de páginas web"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />
                  <Spacing lg="20" md="10" />
                  <Button
                    btnLink="/about"
                    btnText="Páginas de aterrizaje (Landing pages)"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />
                  <Button
                    btnLink="/about"
                    btnText="Plantillas de email"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />

                  <Spacing lg="20" md="10" />
                  <Button
                    btnLink="/about"
                    btnText="Ilustración"
                    variant="cs-type2"
                  />
                  <Spacing lg="0" md="10" />
                </Div>
                <Div className="col-lg-6">
                  <Button
                    btnLink="/about"
                    btnText="Diseño de infografías"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />

                  <Spacing lg="20" md="10" />
                  <Button
                    btnLink="/about"
                    btnText="Banners, folletos, tarjetas"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />
                  <Button
                    btnLink="/about"
                    btnText="Otros servicios de diseño"
                    variant="cs-type2"
                  />
                  <Spacing lg="20" md="10" />


                </Div>
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container cs-shape_wrap_4">
          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-5 col-lg-6">
                <SectionHeading
                  title="Algunas preguntas frecuentes"
                  subtitle="FAQ’s"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-lg-6 offset-xl-1">
                <Accordion />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Creemos algo <br />genial <i>juntos</i> "
            btnText="Contactanos"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
