import Head from 'next/head';
import CaseStudy from '../components/CaseStudy';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Hero3 from '../components/Hero/Hero3';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import MovingText from '../components/MovingText';
import Portfolio2 from '../components/Portfolio/Portfolio2';
import Portfolio3 from '../components/Portfolio/Portfolio3';
import SectionHeading from '../components/SectionHeading';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import Spacing from '../components/Spacing';

export default function CreativePortfolio() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];
  const portfolioData = [
    {
      title: 'Diseño y desarrollo de sitios web de comercio electrónico.',
      subtitle: 'Project 01',
      btnText: 'Ver Detalles',
      btnLink: '/portfolio/portfolio-details',
      imageUrl: '/images/portfolio_35.jpeg',
      category: 'Web Development',
    },
    {
      title: 'Agencia corporativa para un medio ambiente saludable',
      subtitle: 'Project 02',
      btnText: 'Ver Detalles',
      btnLink: '/portfolio/portfolio-details',
      imageUrl: '/images/portfolio_36.jpeg',
      category: 'Branding',
    },
    {
      title: 'Panel de administrador',
      subtitle: 'Project 03',
      btnText: 'Ver Detalles',
      btnLink: '/portfolio/portfolio-details',
      imageUrl: '/images/portfolio_37.jpeg',
      category: 'UI Design',
    },
    {
      title: 'Otro proyecto',
      subtitle: 'Project 04',
      btnText: 'Ver Detalles',
      btnLink: '/portfolio/portfolio-details',
      imageUrl: '/images/portfolio_38.jpeg',
      category: 'Apps Design',
    },
  ];

  return (
    <>
      <Head>
        <title>Home - Portfolio Creativo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero3
          title="LetDev <br />Portfolio"
          btnLink="contact"
          btnText={`Hablemos`}
          socialLinksHeading="Seguinos"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="./images/hero_bg_4.jpeg"
        />
        {/* End Hero Section */}

        {/* Start Portfolio Section */}
        <Spacing lg="150" md="80" />
        {portfolioData.map((item, index) =>
          index % 2 === 0 ? (
            <Div key={index}>
              <Portfolio2
                title={item.title}
                subtitle={item.subtitle}
                btnText={item.btnText}
                btnLink={item.btnLink}
                imageUrl={item.imageUrl}
                category={item.category}
              />
              <Spacing lg="100" md="70" />
            </Div>
          ) : (
            <Div key={index}>
              <Portfolio3
                title={item.title}
                subtitle={item.subtitle}
                btnText={item.btnText}
                btnLink={item.btnLink}
                imageUrl={item.imageUrl}
                category={item.category}
              />
              <Spacing lg="100" md="70" />
            </Div>
          ),
        )}
        {/* End Portfolio Section */}

        {/* Start Case Study Section */}
        <Spacing lg="45" md="10" />
        <Div className="container">
          <SectionHeading
            title="Casos de estudio "
            subtitle="Caso de estudio"
            variant="cs-style1 text-center"
          />
          <Spacing lg="90" md="45" />
        </Div>
        <CaseStudy
          title="Analisis <br /> de eficiencia"
          bgUrl="/images/case_study_2.jpeg"
          href="/case-study-details"
          variant="cs-style2"
        />
        <CaseStudy
          title="Aplicacion de viajes <br /> caso de estudio"
          bgUrl="/images/case_study_1.jpeg"
          href="/case-study-details"
        />
        <Spacing lg="150" md="80" />
        {/* End Case Study Section */}

        {/* Start Testimonial Section */}
        {/* End Testimonial Section */}

        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <MovingText text="Nuestros Clientes" />
        <Spacing lg="105" md="70" />
        {/* End MovingText Section */}

        {/* Start LogoList Section */}
        <Div className="container">
          <LogoList />
        </Div>
        <Spacing lg="150" md="80" />
        {/* End LogoList Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Trabajemos <br />juntos"
            btnText="Solicita una reunion"
            btnLink="/contact"
            bgSrc="/images/cta_bg_3.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
