import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact2 from '../components/FunFact/FunFact2';
import Hero5 from '../components/Hero/Hero5';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import MovingText from '../components/MovingText';
import PricingTableList from '../components/PricingTable/PricingTableList';
import SectionHeading from '../components/SectionHeading';
import ServiceList from '../components/ServiceList';
import PortfolioSlider2 from '../components/Slider/PortfolioSlider2';
import PostSlider from '../components/Slider/PostSlider';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import Spacing from '../components/Spacing';
import VideoModal from '../components/VideoModal';

export default function MarketingAgency() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];
  const funfaceData = [
    {
      title: 'Digital products',
      factNumber: '550',
    },
    {
      title: 'Global happy clients',
      factNumber: '40K',
    },
    {
      title: 'Project completed',
      factNumber: '50k',
    },
    {
      title: 'Team members',
      factNumber: '250',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - Marketing Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero5
          title="Haga crecer su negocio<br /> con una estrategia digital"
          subtitle="Brindamos la mejor solución de resolución de problemas para nuestros clientes y brindamos el mejor producto en el presente y el futuro."
          btnLink="contact"
          btnText="Hablemos"
          socialLinksHeading="Seguinos"
          heroSocialLinks={heroSocialLinks}
        />
        {/* End Hero Section */}

        {/* Start Services Section */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Nuestros Principales Servicios"
            subtitle="Servicios"
            variant="cs-style1 text-center"
          />
          <Spacing lg="70" md="45" />
          <ServiceList />
        </Div>
        {/* End Services Section */}

        {/* Start PortfolioSlider Section */}
        <Spacing lg="120" md="50" />
        <Div className="container">
          <h2 className="cs-font_50 cs-m0 cs-line_height_4">
            Nuestro proceso ágil es la capacidad de adaptarse y responder al cambio.
          </h2>
        </Div>
        <Spacing lg="90" md="70" />
        <PortfolioSlider2 />
        {/* End PortfolioSlider Section */}


        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <MovingText text="Las soluciones que buscas en un solo lugar" />
        <Spacing lg="100" md="70" />
        {/* End MovingText Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Tenes un proyecto <br />en <i>mente</i> ?"
            btnText="Solicita una reunion"
            btnLink="/contact"
            bgSrc="/images/cta_bg_3.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
