import Head from 'next/head';
import React from 'react';
import Hero6 from '../components/Hero/Hero6';
import Layout from '../components/Layout';

export default function ShowcasePortfolio() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];

  const showcaseData = [
    {
      title: 'Soluciones modernas <br/>e innovadoras para empresas',
      imgUrl: '/images/cta_bg_3.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Innovación y practicidad <br/>en un solo lugar',
      imgUrl: '/images/case_study_1.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Soluciones eficientes <br/>para la gestion empresarial',
      imgUrl: '/images/case_study_2.jpeg',
      href: '/case-study-details',
    },
  ];
  return (
    <>
      <Head>
        <title>Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero6
          heroSocialLinks={heroSocialLinks}
          socialLinksHeading="Seguinos"
          showcaseData={showcaseData}
        />
      </Layout>
    </>
  );
}
